In [1]:
import cupy as cp


In [16]:
a = cp.ones((4,3))
print(a)
b = cp.array([2, 1, 3])
            
print(a*b[None, ...])

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 1. 3.]
 [2. 1. 3.]
 [2. 1. 3.]
 [2. 1. 3.]]
